llanguage: python

python:
    - "3.6.3"

services:
    - postgresql

virtualenv:
  env_bin_activate: true

install:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install codecov
    - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
    - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

addons:
    postgresql: "9.6"
    chrome: stable

before_script:
    - psql -c "CREATE DATABASE mydb;" -U postgres

script:
    - whereis google-chrome-stable
    - whereis chromedriver
    - coverage run manage.py test map/tests

after_success:
  - codecov
