language: python

python:
    - "3.6.3"

node_js: '7'

sudo: required

env: DISPLAY=':99.0'

dist: trusty

services:
    - postgresql

virtualenv:
  env_bin_activate: true

install:
    - pip install -r requirements.txt
    - pip install codecov

addons:
    postgresql: "9.6"
    apt:
      sources:
        - google-chrome
      packages:
        - google-chrome-stable

before_script:
    - psql -c "CREATE DATABASE mydb;" -U postgres
    - sh -e /etc/init.d/xvfb start

script:
    - coverage run manage.py test map/tests
    - python3 -m unittest discover -p "test_homepage.py"
    - python3 -m unittest discover -p "test_createpage.py"

after_success:
  - codecov
